apiVersion: v1
kind: Secret
metadata:
  name: meta-data-repository
  namespace: oih-dev-ns
type: Opaque
data:
  mongourl: 'bW9uZ29kYitzcnY6Ly9hZG1pbjpMTkNEWWMyRUt5RUYyUlo4QGNsdXN0ZXIwLm9pdXo1Lm1vbmdvZGIubmV0L215Rmlyc3REYXRhYmFzZT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk='
  iamtoken: 'LVFtelB5UGt1NzhPZkVNclBiTE0wSU1HVlh6MlB1RjVieFZtSUxoXzdRQ2s4Y0FSSERPSVhNdGJTYzEyZ1ctRndPcmxyWW45R3hOdG9zTzR6VlJQclV3SDZfSXdJMGFuTF9VY3VYQ0ZnRkFoRjlEVjBPaXh2cl8wbkJwb3htYUhmNF96cjc4MlRNa1VZTTBzWTJGd1Y3aUx0MGM5ZG92eXhVamp6U0VraU9N'