apiVersion: v1
kind: Secret
metadata:
  name: component-repository
  namespace: oih-dev-ns
type: Opaque
data:
  mongourl: 'bW9uZ29kYitzcnY6Ly9hZG1pbjpMTkNEWWMyRUt5RUYyUlo4QGNsdXN0ZXIwLm9pdXo1Lm1vbmdvZGIubmV0L215Rmlyc3REYXRhYmFzZT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk='
  iamtoken: 'c29tZXN0cmluZw=='